microsoft:
  graph:
    client-id: ${MICROSOFT_CLIENT_ID}
    client-secret: ${MICROSOFT_CLIENT_SECRET}
    tenant-id: ${MICROSOFT_TENANT_ID}
    redirect-uri: ${MICROSOFT_REDIRECT_URI}
    scope: "User.Read Chat.ReadWrite ChatMessage.Send offline_access"
    token-buffer-minutes: 5
    refresh-token-days: 90

# SpringDoc with external swagger.yml
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # Point to external swagger.yml
    url: /swagger.yml
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  show-actuator: false

logging:
  level:
    com.fecredit.gbg: DEBUG