microsoft:
  graph:
    client-id: ${MICROSOFT_CLIENT_ID}
    client-secret: ${MICROSOFT_CLIENT_SECRET}
    tenant-id: ${MICROSOFT_TENANT_ID}
    redirect-uri: ${MICROSOFT_REDIRECT_URI}
    scope: "User.Read Chat.ReadWrite ChatMessage.Send offline_access"
    token-buffer-minutes: 5
    refresh-token-days: 90

logging:
  level:
    com.company.teams: DEBUG