microsoft:
  graph:
    client-id: ${MICROSOFT_CLIENT_ID:c1356023-8356-4a29-9422-7e25033cd3fc}
    client-secret: ${MICROSOFT_CLIENT_SECRET}
    tenant-id: ${MICROSOFT_TENANT_ID:b6260bc1-0228-4c6f-9881-15add8fb5383}
    redirect-uri: ${MICROSOFT_REDIRECT_URI:https://instincthub-uat.fecredit.com.vn/WebClient/Saml2/Acs}
    scope: "User.Read Chat.ReadWrite ChatMessage.Send offline_access"
    token-buffer-minutes: 5
    refresh-token-days: 90

logging:
  level:
    com.company.teams: DEBUG